# Generated by Django 6.1 on 2026-08-22 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=255)),
                ('clinical_notes', models.TextField(help_text='Doctor clinical observations and findings')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('patient_friendly_summary', models.TextField(blank=True, null=True)),
                ('structured_ai_summary', models.JSONField(default=dict, help_text='Structured timetable, warnings, and follow-up guidance')),
                ('ai_post_visit_raw', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appointments.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g. 500mg, 10ml, 1 tablet', max_length=100)),
                ('frequency', models.CharField(choices=[('DAILY', 'Once Daily (1x)'), ('TWICE_DAILY', 'Twice Daily (2x)'), ('THRICE_DAILY', 'Three Times Daily (3x)'), ('FOUR_TIMES_DAILY', 'Four Times Daily (4x)'), ('EVERY_8_HOURS', 'Every 8 Hours'), ('AS_NEEDED', 'As Needed (PRN)')], default='DAILY', max_length=30)),
                ('duration_days', models.PositiveIntegerField(default=5)),
                ('meal_timing', models.CharField(choices=[('BEFORE_MEAL', 'Before Meal'), ('AFTER_MEAL', 'After Meal'), ('WITH_MEAL', 'With Meal'), ('EMPTY_STOMACH', 'On Empty Stomach'), ('ANYTIME', 'Anytime')], default='AFTER_MEAL', max_length=30)),
                ('instructions', models.CharField(blank=True, help_text='e.g. Take with warm water', max_length=255, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('message_text', models.TextField()),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_reminders', to=settings.AUTH_USER_MODEL)),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='prescriptions.prescriptionitem')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
    ]
