# Generated by Django 6.1 on 2026-08-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=150, null=True)),
                ('notification_type', models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('CANCELLATION', 'Appointment Cancellation'), ('LEAVE_CONFLICT', 'Doctor Leave Conflict Cancellation'), ('POST_VISIT_SUMMARY', 'Post-Visit Summary'), ('MEDICATION_REMINDER', 'Medication Reminder')], max_length=40)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('MAX_RETRIES_EXCEEDED', 'Max Retries Exceeded')], default='QUEUED', max_length=30)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=4)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
